version: '3'

services:
  database:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: ${DB_NAME:-app}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_NAME:-app}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data: